name:                hilo
version:             0.1.0.0
github:              "githubuser/hilo"
license:             BSD3
author:              "Craig Asselin"
maintainer:          "asselin.craig@gmail.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            line editor written in Haskell, based on kilo
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hilo#readme>

dependencies:
- base >= 4.7 && < 5
- unix

library:
  source-dirs: src

executables:
  hilo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hilo

tests:
  hilo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hilo
